### ISSUE TITLE
Redmine 4.x [rails 5.x] compatibility

### ISSUE THREAD

**Issue by tarwirdur** [return1/redmine_hide_estimated_hours#21]
Doesn't work with redmine 4.0.3 and rails 5.2:

```
$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for Journal (call 'Journal.connection' to establish a connection):Class
Did you mean?  alias_method
/var/lib/gems/2.3.0/gems/activerecord-5.2.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/var/www/redmine-4/plugins/redmine_hide_estimated_hours/lib/journal_patch.rb:7:in `included'
/var/www/redmine-4/plugins/redmine_hide_estimated_hours/lib/journal_patch.rb:35:in `include'
/var/www/redmine-4/plugins/redmine_hide_estimated_hours/lib/journal_patch.rb:35:in `<top (required)>'
```

I've replaced `alias_method_chain` with `alias_method`. 
And it looks like it works.

I'm not sure that this is correct patch. I don't understand ruby well. Based on [rails documentation](https://apidock.com/rails/ActiveSupport/CoreExtensions/Module/alias_method_chain).

https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/

Full diff:

```diff
diff --git a/lib/journal_patch.rb b/lib/journal_patch.rb
index 0e4f415..b1ce2eb 100644
--- a/lib/journal_patch.rb
+++ b/lib/journal_patch.rb
@@ -6,7 +6,8 @@ module JournalPatch
     base.send(:include, InstanceMethods)
     base.class_eval do
       unloadable # Send unloadable so it will not be unloaded in development
-      alias_method_chain :visible_details, :patch
+      alias_method :visible_details_without_patch, :visible_details
+      alias_method :visible_details, :visible_details_with_patch
     end
   end
 
@@ -32,4 +33,4 @@ module JournalPatch
   end
 end
 
-Journal.send(:include, JournalPatch)
\ No newline at end of file
+Journal.send(:include, JournalPatch)
diff --git a/lib/pdf_patch.rb b/lib/pdf_patch.rb
index d6b3050..d521815 100644
--- a/lib/pdf_patch.rb
+++ b/lib/pdf_patch.rb
@@ -7,7 +7,8 @@ module IssuesPdfHelperPatch
     base.send(:include, InstanceMethods)
     base.class_eval do
       unloadable # Send unloadable so it will not be unloaded in development
-      alias_method_chain :issue_to_pdf, :patch
+      alias_method :issue_to_pdf_without_patch, :issue_to_pdf
+      alias_method :issue_to_pdf, :issue_to_pdf_with_patch
     end
   end
 
diff --git a/lib/query_patch.rb b/lib/query_patch.rb
index b939625..ac1e567 100644
--- a/lib/query_patch.rb
+++ b/lib/query_patch.rb
@@ -6,7 +6,8 @@ module QueryPatch
     base.send(:include, InstanceMethods)
     base.class_eval do
       unloadable # Send unloadable so it will not be unloaded in development
-      alias_method_chain :available_filters, :patch
+      alias_method :available_filters_without_patch, :available_filters
+      alias_method :available_filters, :available_filters_with_patch
     end
   end
 
@@ -28,7 +29,8 @@ module IssueQueryPatch
     base.send(:include, InstanceMethods)
     base.class_eval do
       unloadable # Send unloadable so it will not be unloaded in development
-      alias_method_chain :available_columns, :patch
+      alias_method :available_columns_without_patch, :available_columns
+      alias_method :available_columns, :available_columns_with_patch
     end
   end
```

**Comment by return1** [comment]
thank you for your patch! could you form this into a pull request, so other people can use your fork in the meantime (until i find time to test and merge your changes).

**Comment by return1** [comment]
thank you!

**Comment by liviriniu** [comment]
Thank you, this diff saved the day for me. Needed to adapt an old Redmine plugin to work for 4.2.x versions.
